project:
  type: website
  resources:
    - "assets/*"
    - "recordings/*"
  output-dir: docs/463a01339cf0f456ba54a1849df50d1a22c247e3
  preview:
    port: 4321
  post-render:
    - _pw_protect.py

website:
  favicon: "favicon.png"
  title: ""
  google-analytics: "G-RFMTL6Q5J5"
  sidebar:
    title: |
      DSAN 5100 Section 03 (Thursdays, 12:30-3pm)<br>
      <span class="subtitle">Car Barn 201</span><br>
      <span class="subtitle">Fall 2023, Georgetown</span><br>
      <span class="subtitle">
        Prof. Jeff&nbsp;
        <a href='mailto:jj1088@georgetown.edu' target='_blank'>
          <i class='bi bi-envelope-at ps-1 pe-1'></i>
        </a>
      </span><br>
      <span class='subtitle'>
        <a href='https://georgetown.zoom.us/j/97102554837' target='_blank' class='icon-link' style='text-decoration: none !important;'>
        <span class='icon pe-1'>
          <svg class="bi" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 50 50">
            <path d="M33.619,4H16.381C9.554,4,4,9.554,4,16.381v17.238C4,40.446,9.554,46,16.381,46h17.238C40.446,46,46,40.446,46,33.619	V16.381C46,9.554,40.446,4,33.619,4z M30,30.386C30,31.278,29.278,32,28.386,32H15.005C12.793,32,11,30.207,11,27.995v-9.382	C11,17.722,11.722,17,12.614,17h13.382C28.207,17,30,18.793,30,21.005V30.386z M39,30.196c0,0.785-0.864,1.264-1.53,0.848l-5-3.125	C32.178,27.736,32,27.416,32,27.071v-5.141c0-0.345,0.178-0.665,0.47-0.848l5-3.125C38.136,17.54,39,18.019,39,18.804V30.196z"></path>
          </svg></span>Recurring Zoom Link <i class='bi bi-box-arrow-up-right ps-1'></i>
        </a>
      </span>
    contents:
      - href: "https://jfh.georgetown.domains/dsan5100/"
        text: "<i class=\"bi bi-arrow-left\" style=\"margin-right: 4px\"></i>Main Course Page"
      - "---"
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i> Section 03 Home"
      - href: w01/index.qmd
        text: "Week 1: Aug 24"
      - href: w02/index.qmd
        text: "Week 2: Aug 31"
      - href: w03/index.qmd
        text: "Week 3: Sep 7"
      - href: w04/index.qmd
        text: "Week 4: Sep 14"
      - href: w05/index.qmd
        text: "Week 5: Sep 20"
      - href: w06/index.qmd
        text: "Week 6: Sep 27"
      - href: recordings/index.qmd
        text: "Lecture Recordings"
      - "---"
      - href: extra-videos/index.qmd
        text: "Extra Videos"
      - href: writeups/index.qmd
        text: "Extra Writeups"
      - href: cheatsheet-math.qmd
        text: "Math Cheatsheet"
      - "---"
      - href: "https://georgetown.instructure.com/courses/173333"
        text: "Course Canvas Page <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://calendar.app.google/yMnESMtMNPdKEaPz5"
        text: "Book Office Hours <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://forms.gle/QBT621Vmcez4Y99r5"
        text: "Suggestion Box <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://jjacobs.me/dsps"
        text: "Textbook <i class='bi bi-box-arrow-up-right ps-1'></i>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

