project:
  type: website
  resources:
    - "assets/*"
    - "recordings/*"
  output-dir: docs/463a01339cf0f456ba54a1849df50d1a22c247e3
  preview:
    port: 4321
  post-render:
    - _post_pw_protect.py
    - _post_fix_figures.py
    - _post_recording_pages.py

website:
  title: ""
  sidebar:
    title: "DSAN 5100 Section 03 (Thursdays, 12:30-3pm)"
    contents:
      - href: "https://jfh.georgetown.domains/dsan5100/"
        text: "<i class=\"bi bi-arrow-left\" style=\"margin-right: 4px\"></i>Main Course Page"
      - "---"
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i> Section 03 Home"
      - href: w01/index.qmd
        text: "Week 1: Aug 24"
      - href: w02/index.qmd
        text: "Week 2: Aug 31"
      - href: w03/index.qmd
        text: "Week 3: Sep 7"
      - href: w04/index.qmd
        text: "Week 4: Sep 14"
      - href: w05/index.qmd
        text: "Week 5: Sep 20"
      - href: w06/index.qmd
        text: "Week 6: Sep 27"
      - href: w07/index.qmd
        text: "Week 7: Oct 5"
      - href: w08/index.qmd
        text: "Week 8: Oct 12"
      - href: w09/index.qmd
        text: "Week 9: Oct 19"
      - href: w10/index.qmd
        text: "Week 10: Oct 26"
      - href: w11/index.qmd
        text: "Week 11: Nov 2"
      - href: w12/index.qmd
        text: "Week 12: Nov 9"
      - href: w13/index.qmd
        text: "Week 13: Nov 16"
      - href: recordings/index.qmd
        text: "Lecture Recordings"
      - "---"
      - href: extra-videos/index.qmd
        text: "Extra Videos"
      - href: writeups/index.qmd
        text: "Extra Writeups"
      - href: cheatsheet-math.qmd
        text: "Math Cheatsheet"
      - "---"
      - href: "https://georgetown.instructure.com/courses/173333"
        text: "Course Canvas Page <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://calendar.app.google/yMnESMtMNPdKEaPz5"
        text: "Book Office Hours <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://forms.gle/QBT621Vmcez4Y99r5"
        text: "Suggestion Box <i class='bi bi-box-arrow-up-right ps-1'></i>"
      - href: "https://jjacobs.me/dsps"
        text: "Textbook <i class='bi bi-box-arrow-up-right ps-1'></i>"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://code.jquery.com/jquery-3.7.1.slim.min.js'></script><script src='/jjcustom.js'></script>"
