---
title: "Week 5: Continuous Probability Distributions"
subtitle: "*DSAN 5100: Probabilistic Modeling and Statistical Computing*<br>Section 03"
author: "Jeff Jacobs"
institute: "<a href=\"mailto:jj1088@georgetown.edu\" target=\"_blank\">`jj1088@georgetown.edu`</a>"
date: 2023-09-21
date-format: full
#date: last-modified
#date-format: "dddd MMM D, YYYY, HH:mm:ss"
lecnum: 5
categories:
  - "Class Sessions"
format:
  revealjs:
    html-math-method: mathjax
    slide-number: true
    #cache: true
    output-file: slides.html
    theme: [default, "../_jjslides.scss"]
  html:
    cache: true
    output-file: index.html
    html-math-method: mathjax
metadata-files: 
  - "../_slide-meta.yml"
---


# Schedule {.smaller .smaller-title data-name="Schedule"}

::: {.hidden}

```{r}
source("../_globals.r")
```

:::

Today's Planned Schedule (Section 03)

| | Start | End | Topic | Recording |
|:- |:- |:- |:- |:-:|
| **Lecture** | 12:30pm | 12:40pm | [Recap &rarr;](#recap) | <a href="./recording-w03-1.html" target="_blank" class="disabled"><i class="bi bi-film"></i></a> |
| | 12:40pm | 1:20pm | [Continuous Distributions (Biting the Bullet) &rarr;](#continuous-distributions-biting-the-bullet) | <a href="./recording-w03-2.html" target="_blank" class="disabled"><i class="bi bi-film"></i></a> |
| | 1:20pm | 2:00pm | [Common Continuous Distributions &rarr;](#common-continuous-distributions) | <a href="./recording-w03-3.html" target="_blank" class="disabled"><i class="bi bi-film"></i></a> |
| **Break!** | 2:00pm | 2:10pm | | |
| **Lab** | 2:10pm | 2:50pm | [Lab 4 Demonstration <i class="bi bi-box-arrow-up-right" style="font-size: 1.2rem;"></i>](https://jfh.georgetown.domains/dsan5100/share-point/labs/lab-1/lab-1-demo.html){target="_blank"} | <a href="./recording-w03-4.html" target="_blank" class="disabled"><i class="bi bi-film"></i></a> |
| | 2:50pm | 3:00pm | [Lab 4 Assignment Overview <i class="bi bi-box-arrow-up-right" style="font-size: 1.2rem;"></i>](https://jfh.georgetown.domains/dsan5100/share-point/labs/lab-1/lab-1-assignment.html){target="_blank"} | <a href="./recording-w03-5.html" target="_blank" class="disabled"><i class="bi bi-film"></i></a> |
| | 2:40pm | 3:00pm | Student Presentation |  |

: {tbl-colwidths="[12,12,12,54,5,5]"}

# Recap {data-stack-name="Recap"}

* What things have distributions?
* PDFs, CDFs

## What Things Have Distributions?

* Answer: **Random Variables**

## CDFs/pdfs/pmfs: *What* Are They? {.smaller}

* Functions which **answer questions** about a **Random Variable** ($X$ in this case)
* **CDF**: What is probability of value **less than or equal to $X$**?

$$
F_X(v_X) \overset{\text{defn}}{=} \Pr(X \leq v_X)
$$

* **pmf**: What is the probability of **this exact value**? (Discrete only)

$$
p_X(v_X) = \Pr(X = v_X)
$$

* **pdf**: ...It's the thing you integrate to get the CDF

$$
f_X(v_X) = \frac{d}{dv_X}F_X(v_X) \iff \int f_X(v_X)dv_X = F_X(v_X)
$$

## CDFs/pdfs/pmfs: *Why* Do We Use Them? {.smaller}

* CDF is like the "API" that allows you to access **all of the information about the distribution** (pdf/pmf is derived from the CDF)
* Example: we know there's some "thing" called the *Exponential Distribution*...
* How do we **use** this distribution to understand a random variable $X \sim \text{Exp}$?
  * Answer: the **CDF** of $X$!
  * Since **all exponentially-distributed RVs have the same PDF**, we can call this PDF **"the" exponential distribution**
* Say we want to find the **median** of $X$: The median is the number $m$ satisfying

$$
\Pr(X \leq m) = \frac{1}{2}, \; \Pr(X \geq m) = \frac{1}{2}
$$

## Finding a Median via the CDF

::: {.callout-note title="Median of a Random Variable $X$"}

The **median** of a random variable $X$ with some CDF $F_X(v_X)$ is the [set of] numbers $m$ for which the probability that $X$ is **lower than** $m$ is the same as the probability that $X$ is **greater than** $m$:

$$
\begin{align*}
\text{Median}(X) &= \left\{m \mid F_X(m) = 1 - F_X(m) \right\} \\
&= \left\{m \mid \int_{-\infty}^{m}f_X(v_X)dv_X = \int_{m}^{\infty}f_X(v_X)dv_X \right\}
\end{align*}
$$

:::

**Example**:

# Continuous Distributions (Biting the Bullet) {data-stack-name="Continuous Dists"}

## What is a pdf?

* Answer: Has no meaning outside of its **context**: a **random variable** with a **CDF** giving the distribution of its possible values

# Common Continuous Distributions {data-stack-name="Normal Dist"}

## Normal Distribution {data-name="Normal"}

## Uniform Distribution {data-name="Uniform"}

## Exponential Distribution {data-name="Exponential"}

## Cauchy Distribution {data-name="Cauchy"}



# Lab {data-name="Lab"}